# Generated by Django 4.0.4 on 2022-05-18 18:31

import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('real', models.DecimalField(decimal_places=25, max_digits=30)),
                ('euro', models.DecimalField(decimal_places=25, max_digits=30)),
                ('iene', models.DecimalField(decimal_places=25, max_digits=30)),
                ('date', models.DateField(default=datetime.datetime.now, error_messages={'unique': 'Cotações já importadas!'}, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
